


- name: Refresh Docker Version
  become: true
  shell: "sudo apt-get install docker-ce=18.06.1~ce~3-0~ubuntu -y --force-yes"
  ignore_errors: yes

- name: Install Python
  apt:
    name: python
    state: present
  ignore_errors: yes

- name: install python-pip
  apt:
    name: python-pip
    state: present
  ignore_errors: yes

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
  ignore_errors: yes

- name: install python-docker
  apt:
    name: python-docker
    state: present
  ignore_errors: yes

- name: Install Docker Module for Python
  pip:
    name: docker
  ignore_errors: yes

- name: Print Variables Test
  shell: "echo hello {{ rabbit_user }} "
  ignore_errors: yes


